---
- name: understanding parameters
  hosts: all
  become: yes
  tasks:
    - name: print ansible_host
      debug:
        var: ansible_host
    - name: print other parameters
      debug: 
        msg: "ansible_port = {{ ansible_port }} ansible_user = {{ ansible_user }}"