---
- name: installing tomcat
  hosts: appserver
  become: yes
  tasks:
    - name: installing java on ubuntu
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: adduser in tomcat
      user:
        name: tomcat
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url: 
        url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz"
        dest: "/tmp/apache-tomcat-8.5.78.tar.gz"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat
      unarchieve: 
        src: "/tmp/apache-tomcat-8.5.78.tar.gz"
        dest: "/opt/tomcat"
      when: ansible_facts['distribution'] == "Ubuntu"