---
- name: installing tomcat on ubuntu
  become: yes
  hosts: appserver
  vars_files:
    - vars/ubuntu_vars.yaml
  tasks:
    - name: installing java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: useradd tomcat
      user:
        name: tomcat
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: archieve tomcat
      unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_install-path }}"
      when: ansible_facts['distribution'] == "Ubuntu"
        