---
- name: installing tomcat on ubuntu
  become: yes
  hosts: appserver
  vars:
    username: tomcat
    java_package: openjdk-8-jdk
  vars_files:
    - vars/ubuntu_vars.yaml
  tasks:
    - name: installing java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add group
      group:
        name: "{{ username }}"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: adduser tomcat
      user:
        name: "{{ username }}"
        home: "{{ tomcat_install_path }}"
        group: "{{ username }}"
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat
      unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_install_path }}"
        remote_src: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: added files
      file:
        src: /opt/tomcat/apache-tomcat-8.5.61.tar.gz
        dest: /opt/tomcat/latest
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link
      

        
        