---
- name: installing tomcat on ubuntu
  become: yes
  hosts: appserver
  tasks:
    - name: installing java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: useradd tomcat
      user:
        name: tomcat
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.zip"
        dest: "/tmp/apache-tomcat-8.5.78.tar.gz"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: archieve tomcat
      unarchive:
        src: "/tmp/apache-tomcat-8.5.78.tar.gz"
        dest: "/opt/tomcat"
      when: ansible_facts['distribution'] == "Ubuntu"
        