---
- name: installing tomcat on ubuntu
  hosts: appserver
  become: yes
  tasks:
    - name: installing java on ubuntu
      apt: 
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"