---
- name: installing tomcat on ubuntu
  hosts: appserver
  become: yes
  tasks:
    - name: installing java on ubuntu
      apt: 
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Ensure group "somegroup" exists
      group:
        name: tomcat
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: creating user
      user: 
        name: tomcat
        home: /opt/tomcat/
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: get url
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.8/bin/apache-tomcat-10.0.8.tar.gz"
        dest: "/tmp/apache-tomcat-10.0.8.tar.gz"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: unzip
      package:
        name: unzip
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat
      unarchive:
        src: "/tmp/apache-tomcat-10.0.8.tar.gz"
        dest: "/opt/tomcat/"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: mv tomcat
      copy: 
        src: "/tmp/apache-tomcat-10.0.8.tar.gz"
        dest: "/opt/tomcat/"
      when: ansible_facts['distribution'] == "Ubuntu"

      