---
- name: install lampstack on ubuntu and centos
  hosts: webserver
  become: yes
  tasks:
    - name: install lampstack
      package:
        name: "{{ package_name }}"
        state: present
    - name: install php packages
      package:
        name: "{{ Item }}"
        state: present
      loop: "{{ php_packages}}"
    