---
- name: installing utility packages
  hosts: all
  become: yes
  tasks:
    - name: install git
      package:
        name: git
        state: present
    - name: install nano
      package:
        name: nano
        state: present
    - name: install tree
      package:
        name: tree
        state: present
- name: apache on centos
  hosts: centos
  become: yes
  tasks:
    - name: install apache
      package:
        name: apache
        enable: yes
        state: started
 